services:
  fichedepute:
    build: .
    container_name: fichedepute
    restart: unless-stopped
    network_mode: host
    environment:
      - PORT=10091
      - SITE_BRAND=fr
      - VAR_DIR=/app/var
    volumes:
      - ./var:/app/var
